mqtt:
  enable: true
  name: "hoval-gateway"
  topic: "hoval-gw-new"
  port: 8883

periodic_requests:
  - device_type: 10
    device_id: 8
    periodic_time: 30
    priority: 208
    datapoints:
      - betriebswahl_lueftung

datapoints:
  - name: betriebswahl_lueftung
    function_group: 50
    function_number: 0
    datapoint_id: 40650
    type: LIST
  - name: normal_lueftungs_modulation
    function_group: 50
    function_number: 0
    datapoint_id: 40651
    type: LIST
  - name: normal_lueftungs_modulation
    function_group: 50
    function_number: 0
    datapoint_id: 40651
    type: LIST
  - name: spar_lueftungs_modulation
    function_group: 50
    function_number: 0
    datapoint_id: 40686
    type: LIST
  - name: lueftungs_modulation
    function_group: 50
    function_number: 0
    datapoint_id: 38606
    type: LIST
  - name: feuchte_sollwert
    function_group: 50
    function_number: 0
    datapoint_id: 40687
    type: U16
    decimal: 1
  - name: feuchtigkeit_abluft
    function_group: 50
    function_number: 0
    datapoint_id: 37600
    type: U16
    decimal: 1
  - name: temperature_outside_air
    function_group: 50
    function_number: 0
    datapoint_id: 0
    type: S16
    decimal: 1
  - name: temperature_exhaust_air
    function_group: 50
    function_number: 0
    datapoint_id: 37602
    type: S16
    decimal: 1
  - name: name_of_hv
    function_group: 0
    function_number: 0
    datapoint_id: 4005
    type: STR
